openapi: "3.0.2"
info:
  title: Payments Service
  description: A service to handle the order payments
  version: 1.0.0
  contact:
    name: API SUPPORT
    email: apisupport@example.com
  license:
    name: MIT License
    url: https://mit-license.org/

servers:
- url: http://{basepath}:{port}/payments-service/api/v1
  description: Internal Microservices Api Server
  variables:
    basepath:
      default: localhost
    port:
      enum:
        - '7050'
      default: '7050'
- url: http://{basepath}:{port}/{prefix}/payments/api/v1
  description: Gateway Api Server
  variables:
    basepath:
      default: localhost
    port:
      enum:
        - '9000'
      default: '9000'
    prefix:
      enum:
        - public
        - private
      default: private

components:
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    GenericError:
      description: Generic Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    id_int64Unsigned:
      type: integer
      format: int64
      minimum: 0
      maximum: 9223372036854775807
      readOnly: true
    floatPrice:
      description: price in float
      type: number
      format: float
      minimum: 0
      maximum: 1000
    timestamp:
      type: string
      format: date-time
      example: "2021-01-30T08:30:00Z"
    safetextName:
      description: Safe text for Name
      type: string
      pattern: '^[a-zA-Z0-9 .-]+$'
      minLength: 3
      maxLength: 50
    safetextMessages:
      description: Safe text for Description
      type: string
      pattern: '^[a-zA-Z0-9 .-]+$'
      minLength: 3
      maxLength: 100
    Error:
      type: object
      additionalProperties: false
      description: Error Details
      properties:
        errorCode:
          type: string
          pattern: '^[a-zA-Z0-9]{4}$'
          minLength: 4
          maxLength: 4
        errors:
          type: array
          items:
              $ref: '#/components/schemas/safetextMessages'
        datetime:
          $ref: '#/components/schemas/timestamp'
      required:
        - errorCode
        - errors
        - datetime
      example:
        code: WS01
        errors: 
            - Generic Error
        datetime: "2021-01-30T08:30:00Z"
    Payment:
      type: object
      additionalProperties: false
      description: Error Details
      properties:
        idOrder:
          $ref: '#/components/schemas/id_int64Unsigned'
        price:
          $ref: '#/components/schemas/floatPrice'
        accepted:
          type: boolean      
        transactionTs:
          $ref: '#/components/schemas/timestamp'
        transactionCode:
          $ref: '#/components/schemas/safetextMessages'
        userId:
          $ref: '#/components/schemas/safetextMessages'
        refundedDescription:
          $ref: '#/components/schemas/safetextMessages'
        refunded:
          type: boolean      
        refundedTs:
          $ref: '#/components/schemas/timestamp'
      required:
        - idOrder
        - price
        - confirmed
      example:
        idOrder: 2
        price: 40.00
        accepted: true
        
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

security: 
  - BearerAuth: []

paths:
  /payment/{orderId}:
    get:
      operationId: getPayment
      summary: Retrieve the payment status by orderId
      tags:
        - OrderPayments
      parameters:
        - name: orderId
          in: path
          required: true
          description: the identify of the the order related to payment
          schema:
            $ref: '#/components/schemas/id_int64Unsigned'
      responses:
        200:
          description: The Stock element
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/GenericError'
  /payment/{orderId}/confirm:
    post:
      summary: Confirm payment
      operationId: confirmPaymentOrder
      tags:
        - OrderPayments
      parameters:
        - name: orderId
          in: path
          required: true
          description: the identify of the the order related to payment
          schema:
            $ref: '#/components/schemas/id_int64Unsigned'
      responses:
        200:
          description: A payment Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Payment"
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/GenericError'
  /payment/{orderId}/reject:
    post:
      summary: reject payment
      operationId: rejectPaymentOrder
      tags:
        - OrderPayments
      parameters:
        - name: orderId
          in: path
          required: true
          description: the identify of the the order related to payment
          schema:
            $ref: '#/components/schemas/id_int64Unsigned'
      responses:
        200:
          description: A payment Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Payment"
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/GenericError'
