server:
  servlet:
    context-path: /${spring.application.name}
  port: ${WAREHOUSE_SERVICE_PORT:7000}
  shutdown: graceful
  tomcat:
    connection-timeout: 5s
    threads:
      max: 100
      min-spare: 10

db:
  username: ${DB_WAREHOUSE_USERNAME:aqstore_warehouse}
  password: ${DB_WAREHOUSE_USERNAME:aqstore_warehouse}
  port: ${DB_WAREHOUSE_PORT:5434}
  host: ${DB_WAREHOUSE_HOST:localhost}
  schema: ${DB_WAREHOUSE_SCHEMA:aqstore_warehouse}
  endpoint: postgresql://${db.host}:${db.port}/${db.schema}


logging:
  level:
    root: INFO
#    kafka.*: WARN
#    org.springframework.*: INFO
#    org.neo4j.*: INFO
#    org.apache.kafka.*: WARN
#    

spring:
  application:
    name: warehouse-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
    
  security:
    oauth2:
      resourceserver:
        jwt:
           issuer-uri: http://localhost:8090/auth/realms/aqstore-spring-realm
    
  datasource:
    username: ${db.username}
    password: ${db.password}
    url: jdbc:${db.endpoint}
    hikari:
      pool-name: db_warehouse_pool
      connection-timeout: 5000
      maximum-pool-size: 10     
  flyway:
    user: ${db.username}
    password: ${db.password}
    url: jdbc:${db.endpoint}
    locations: "classpath:/db/migration"
    
  cloud:
    stream:
      function: 
        definition: orderCheckItemsConsumer;
        
      source: productProducer; orderSagaProducer ##cqrs producers
      bindings:
        productProducer-out-0:  ##spring naming convention -> sourceName-
          destination: products
          producer:
            auto-startup: false
            required-groups: catalogsGroup
        orderCheckItemsConsumer-in-0:
          destination: order.items
          group: warehouseGroup
        orderSagaProducer-out-0:
          destination: order.saga
          producer:
            auto-startup: false

 
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:admin}
    password: ${RABBIT_PASSWORD:admin}
    connection-timeout: 15s