openapi: "3.0.2"
info:
  title: Catalog Service
  description: A service used to retrieve products and shipping informations
  version: 1.0.0
  contact:
    name: API SUPPORT
    email: apisupport@example.com
  license:
    name: MIT License
    url: https://mit-license.org/
servers:
- url: http://{basepath}:{port}/{prefix}/catalog/api/v1
  description: Gateway Api Server
  variables:
    basepath:
      default: localhost
    port:
      enum:
        - '9000'
      default: '9000'
    prefix:
      enum:
        - public
        - private
      default: private
- url: http://{basepath}:{port}/catalog-service/api/v1
  description: Internal Microservices Api Server
  variables:
    basepath:
      default: localhost
    port:
      enum:
        - '7010'
        - '7011'
        - '7012'
      default: '7010'


components:
  parameters:
    query_limit:
      name: limit
      in: query
      required: false
      description: The  size of items to return
      schema:
        $ref: '#/components/schemas/limitPerPage'
    query_page:
      name: page
      in: query
      required: false
      description: Number of the page to return
      schema:
        $ref: '#/components/schemas/page'
    query_filter:
      name: filter
      in: query
      required: false
      description: Filter items by text
      schema:
        $ref: '#/components/schemas/safetextName'
        
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    GenericError:
      description: Generic Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  
  
  schemas:
    timestamp:
      type: string
      format: date-time
      example: "2021-01-30T08:30:00Z"
    int16Unsigned:
      type: integer
      format: int16
      minimum: 0
      maximum: 32767
    int64Unsigned:
      type: integer
      format: int64
      minimum: 0
      maximum: 9223372036854775807
    id_int64Unsigned:
      type: integer
      format: int64
      minimum: 0
      maximum: 9223372036854775807
      readOnly: true
    limitPerPage:
      description: the limit of the items to return
      type: integer
      format: int16
      minimum: 1
      maximum: 50
      default: 25
    floatPrice:
      description: price in float
      type: number
      format: float
      minimum: 0
      maximum: 1000
    intWeight:
      description: weight size
      type: integer
      format: int16
      minimum: 1
      maximum: 40
    page:
       type: integer
       format: int16
       minimum: 1
       maximum: 32767
       default: 1  
    safetextName:
      description: Safe text for Name
      type: string
      pattern: '^[a-zA-Z0-9 .-]+$'
      minLength: 3
      maxLength: 50
    safetextMessages:
      description: Safe text for Name
      type: string
      pattern: '^[a-zA-Z0-9 .-]+$'
      minLength: 3
      maxLength: 100
    Error:
      type: object
      additionalProperties: false
      description: Error Details
      properties:
        errorCode:
          type: string
          pattern: '^[a-zA-Z0-9]{4}$'
          minLength: 4
          maxLength: 4
        errors:
          type: array
          items:
              $ref: '#/components/schemas/safetextMessages'
        datetime:
          $ref: '#/components/schemas/timestamp'
      required:
        - errorCode
        - errors
        - datetime
      example:
        code: WS01
        errors: 
            - Generic Error
        datetime: "2021-01-30T08:30:00Z"
    CatalogProduct:
      type: object
      additionalProperties: false
      description: Product's info
      properties:
        id:
          $ref: '#/components/schemas/id_int64Unsigned'
        productName:
          $ref: '#/components/schemas/safetextName'
        description:
          $ref: '#/components/schemas/safetextMessages'
        availability:
            type: boolean
        price:
          $ref: '#/components/schemas/floatPrice'
        productType:
          $ref: '#/components/schemas/safetextName'
        brand:
          $ref: '#/components/schemas/safetextName'
        weight:
          $ref: '#/components/schemas/intWeight'

      required:
        - productName
        - availability
        - description
        - price
        - productType
        - brand
        - weight
      example:
        id: 1
        productName: Playstation 5 Digital
        description: La console di ultima generazione
        price: 499
        availability: true
        productType: GAMING
        weight: 10
        brand: Sony

    CatalogProducts:
      type: object
      additionalProperties: false
      description: List of products
      properties:
        hasNextPage:
            type: boolean
        totalItems:
          $ref: '#/components/schemas/int64Unsigned'
        itemsLimitPerPage:
          $ref: '#/components/schemas/limitPerPage'
        itemsInCurrentPage:
          $ref: '#/components/schemas/limitPerPage'
        totalPage:
          $ref: '#/components/schemas/int16Unsigned'
        currentPage:
          $ref: '#/components/schemas/int16Unsigned'
        nextPage:
          $ref: '#/components/schemas/int16Unsigned'
        products:
          type: array
          items:
            $ref: '#/components/schemas/CatalogProduct'
    CatalogShippingMethod:
      type: object
      additionalProperties: false
      description: Shipping's info
      properties:
        id:
          $ref: '#/components/schemas/id_int64Unsigned'
        shippingName:
          $ref: '#/components/schemas/safetextName'
        duration:
          $ref: '#/components/schemas/safetextMessages'
        price:
          $ref: '#/components/schemas/floatPrice'
        maxWeight:
          $ref: '#/components/schemas/int16Unsigned'
      required:
        - id
        - shippingName
        - duration
        - price
        - maxWeight
      example:
        id: 60a37ac1-c7b2-4b32-8557-d8aba5bdd47d
        productName: Corriere Espresso
        duration: 24/48 ore
        price: 9
        maxWeight: 30
    CatalogShippingMethods:
      type: object
      additionalProperties: false
      description: List of Shipping methods
      properties:
        shippingMethods:
          type: array
          items:
            $ref: '#/components/schemas/CatalogShippingMethod'
        
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

security: 
  - BearerAuth: []          

paths:
  /shippings:
    get:
      summary: List all shipping methods
      operationId: listshippings
      tags:
        - Shipping
      responses:
        200:
          description: "A list of shippings methods"
          content:
            application/json:
              schema:
               $ref: "#/components/schemas/CatalogShippingMethods"
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/GenericError'      
  /products:
    get:
      summary: List all products
      operationId: listproducts
      tags:
        - Product
      parameters:
        - $ref: '#/components/parameters/query_limit'
        - $ref: '#/components/parameters/query_page'
        - $ref: '#/components/parameters/query_filter'

      responses:
        200:
          description: "A list of products"
          content:
            application/json:
              schema:
               $ref: "#/components/schemas/CatalogProducts"
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/GenericError'
  /products/{productId}:
    get:
      summary: Specified product details
      operationId: show Product by Id
      tags:
        - Product
      parameters:
        - name: productId
          in: path
          required: true
          description: the identify of product to retrieve
          schema:
            $ref: '#/components/schemas/id_int64Unsigned'
      responses:
        200:
          description: Response if valid identify
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CatalogProduct"
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/GenericError'


